// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("registry");

export declare const azureClientId: string | undefined;
Object.defineProperty(exports, "azureClientId", {
    get() {
        return __config.get("azureClientId");
    },
    enumerable: true,
});

export declare const azureClientSecret: string | undefined;
Object.defineProperty(exports, "azureClientSecret", {
    get() {
        return __config.get("azureClientSecret");
    },
    enumerable: true,
});

export declare const azureTenantId: string | undefined;
Object.defineProperty(exports, "azureTenantId", {
    get() {
        return __config.get("azureTenantId");
    },
    enumerable: true,
});

export declare const registryBaseUrl: string | undefined;
Object.defineProperty(exports, "registryBaseUrl", {
    get() {
        return __config.get("registryBaseUrl");
    },
    enumerable: true,
});

