"use strict";
// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
exports.__esModule = true;
var pulumi = require("@pulumi/pulumi");
var __config = new pulumi.Config("registry");
Object.defineProperty(exports, "azureClientId", {
    get: function () {
        return __config.get("azureClientId");
    },
    enumerable: true
});
Object.defineProperty(exports, "azureClientSecret", {
    get: function () {
        return __config.get("azureClientSecret");
    },
    enumerable: true
});
Object.defineProperty(exports, "azureTenantId", {
    get: function () {
        return __config.get("azureTenantId");
    },
    enumerable: true
});
Object.defineProperty(exports, "registryBaseUrl", {
    get: function () {
        return __config.get("registryBaseUrl");
    },
    enumerable: true
});
