// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetAzureClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "registry:azureClientId")
}
func GetAzureClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "registry:azureClientSecret")
}
func GetAzureTenantId(ctx *pulumi.Context) string {
	return config.Get(ctx, "registry:azureTenantId")
}
func GetRegistryBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "registry:registryBaseUrl")
}
