// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package registry

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupRegistryResource(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupRegistryResourceResult, error) {
	var rv LookupRegistryResourceResult
	err := ctx.Invoke("registry:index/getRegistryResource:GetRegistryResource", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by GetRegistryResource.
type LookupRegistryResourceResult struct {
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}
