"use strict";
// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
exports.__esModule = true;
exports.getRegistryResource = void 0;
var pulumi = require("@pulumi/pulumi");
var utilities = require("./utilities");
function getRegistryResource(opts) {
    if (!opts) {
        opts = {};
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("registry:index/getRegistryResource:GetRegistryResource", {}, opts);
}
exports.getRegistryResource = getRegistryResource;
